apiVersion: viaduct.ai/v1
kind: ksops

metadata:
  name: immich-secret
  namespace: media
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops

files:
  - ./immich-secret.enc.yaml