apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: media
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:oub4NJpQj/oTTdZGsPW7epViVk2eY+ism6q0bnuIOto=,iv:QcSCL6niJzbRdPmrkPcGnZ80h9Qr3k5qrVSvksfJMzw=,tag:Xy0j3ZZ6IRb5qg4u7JEWiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRWFqZDhZQWJhdFdTOUQx
            bTdKNGgwZXlGeENPRVk4WVlMY3ArblJnR3lnCmRGVjZaUThkK3NCY2M4ZUdtRWsw
            K05memZBaXpIVlVZRHNvVDVMejluejgKLS0tIEZKN0UzYjhOSk9LT25pTTJvM2wv
            Q3kxOGE5cWR3OWNJWHRzOFNCQmJ2a2cKbY+fo/00JeblMTcjF5QcuOfvxGQyvlP0
            /XvEdZBxN56sFmLAWwG3WkwtwxPUlUuXWshoZE9uFtOUPl383lCrhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rvqfv9w738ucl3w8fctvp30p738s72t682dg5vwws5laxm3ek94qlczs34
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T21:04:20Z"
    mac: ENC[AES256_GCM,data:yuvqvU83FsPxuZ9k+AdYz396bLKlN+27ToV2dwD0kf5pu53Ggz3+Widq02KRCmBNplUiKiDoGJmBp22PEZu3mSeyWoWCf112u4Ty2X9vlPpHMVxjFnsqRsN5R4i12zTNaHADqH279071zDLu36NOzAzkubVR8q42nhsB8C41l9Q=,iv:4McPI57Om+NIo6f9pNHSy+P627KPjT3YVGNdPQR3PK0=,tag:QA2XgJ38oSmQPZTAO6HVMw==,type:str]
    version: 3.13.3
