apiVersion: v1
kind: Service
metadata:
  name: kavita
  namespace: media
  labels:
    app: kavita
spec:
  type: NodePort           # keeps a ClusterIP too → Ingress/domain still works
  selector:
    app: kavita
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500      # LAN access: http://<node-LAN-IP>:30500
