apiVersion: v1
kind: Secret
metadata:
    name: degoog-secret
    namespace: apps
type: Opaque
stringData:
    DEGOOG_SETTINGS_PASSWORDS: ENC[AES256_GCM,data:xmHCzr2IJU/OU6bu+g==,iv:7HOxKRn6PN4Rik3NfsN3fot/16QwcEg1nQ7pYlgpAT4=,tag:gjxd6J4abXi8VuFgm4zRpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b0FidEFTZXZUZ1pZWGl5
            QUM0cW8yU3QrakhDenk1ZjVhbXIvT2Q5elVvCmNRaGpvdm1BRDRHcHFHWmxlSzZB
            Z3F4dlRSbDFnTDlkb21UdzBtaUVSRXMKLS0tIFJjVW5YYzBiWEhWaFJXNGZ3djRu
            Q2tXcDI0WnR5WjRHZHJISXE1VTJaaGsKg+K0G0h5XVc6zYl3LzaUG+UjnOZzhjRT
            UefKbhV2x64IObqE6gG6Z2PTtKRCjMVm/JGtdXl5MAsp0F8d7PZouw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rvqfv9w738ucl3w8fctvp30p738s72t682dg5vwws5laxm3ek94qlczs34
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T18:16:37Z"
    mac: ENC[AES256_GCM,data:WMazMIc5J1VQ3fpWG7iCsdhCbLENQ05+8BZ1n97UBLr2srQTRnjtPbLPenzqKiHHcct/DLAU2SySoxyJKWnWvyOEoDn9F0h5ji9Sjo3XBmTUI0ojyRSHuVC6SlYuGM/98KQSBW3L25UHdYk3woNpEPj5cRRGHsZw47d5BzLNBSE=,iv:Z/2e+SZqiwnVCM+NzElWq3cmLCHqa9n28sUrgwy8X80=,tag:uAkIPzb2wnTkZ1dE3+C1Pw==,type:str]
    version: 3.13.3
