apiVersion: v1
kind: Secret
metadata:
    name: degoog-secret
    namespace: apps
type: Opaque
stringData:
    DEGOOG_SETTINGS_PASSWORDS: ENC[AES256_GCM,data:5dnb6nPQnWB5mxTXRw==,iv:mkiMqKZFeCwgQqCJSQb/eInTQs3WerpfHBX/YP9ySPM=,tag:h/XJJTYjJ0xrKd9mSlB2OQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aTVWS1VzZmFRWElYOHdq
            YnU5K3ZjU0dyb3REajVocjJQUm55VGNLTGs0CjBIZFJqdGNhb29mUTVNWTdXaW9n
            Sk1Vc0NJQXFtUkJkOG9UZXJTY2RmQ0kKLS0tIG1GbkxKVzBNamlDZnFvM0lUckxW
            dDg2aXFQaVk2Z21wNVVxT2V3dko1Nm8K/wKUAQuP07oQ8jMcKr5BSYSmDjLTGw+I
            z3E/TYOyGcFOuLtrg4DV4eLh0M+QPxjgZntXgrDm3C4/GdhRDRakKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rvqfv9w738ucl3w8fctvp30p738s72t682dg5vwws5laxm3ek94qlczs34
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T16:57:01Z"
    mac: ENC[AES256_GCM,data:sbJvX3sPCNGUlD42nwmMgNQYlOkeahbKns2NnJaYteM1OmjjeHTQIYbQjSzI7RGgMMUjfIv81fr7zo4hiD4IHwWtLyFTLTApNWXM7z9fz7vflJGa+LSK8MMu5sUW1BlgRySGvzirwXRgVy/hirzUczc09O81AlVgY1LNJVQVbPQ=,iv:xkeEMy5+me+7hSfnjP5hRacr2DekSa77vD+k/107E3o=,tag:7BsLG1LB0/ho4671KeqI7w==,type:str]
    version: 3.13.3
