apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: degoog-secret
  namespace: apps
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops

files:
  - ./degoog-secret.enc.yaml