apiVersion: apps/v1
kind: Deployment
metadata:
  name: degoog
  namespace: apps
  labels:
    app: degoog

spec:
  replicas: 1

  selector:
    matchLabels:
      app: degoog

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: degoog

    spec:
      securityContext:
        fsGroup: 1000

      # Runs before the main degoog container.
      # Makes sure /app/data belongs to UID/GID 1000.
      initContainers:
        - name: fix-perms

          image: busybox:1.38

          command:
            - sh
            - -c
            - |
              chown -R 1000:1000 /app/data

          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN

          volumeMounts:
            - name: data
              mountPath: /app/data

      containers:
        - name: degoog

          image: ghcr.io/degoog-org/degoog:latest

          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 4444
              protocol: TCP

          env:

            # Get the password from the Kubernetes Secret.
            - name: DEGOOG_SETTINGS_PASSWORDS
              valueFrom:
                secretKeyRef:
                  name: degoog-secret
                  key: DEGOOG_SETTINGS_PASSWORDS

            # Don't operate as a public instance.
            - name: DEGOOG_PUBLIC_INSTANCE
              value: "false"

            # Connect to external Valkey (Redis) instance at 192.168.68.103. Change thius later!!!!
            - name: DEGOOG_VALKEY_URL
              value: "redis://redis:7jDtb86VyDd155XM7KHg4UNlahRVyl4s@192.168.68.103:6379"

          resources:
            requests:
              cpu: 50m
              memory: 128Mi

            limits:
              memory: 512Mi

          volumeMounts:
            - name: data
              mountPath: /app/data

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: degoog-data



            #