apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: degoog-data
  namespace: apps
  labels:
    app: degoog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path