apiVersion: v1
kind: Service
metadata:
  name: degoog-valkey
  namespace: apps
  labels:
    app: degoog-valkey

spec:
  type: ClusterIP

  selector:
    app: degoog-valkey

  ports:
    - name: redis
      port: 6379
      targetPort: 6379