apiVersion: apps/v1
kind: Deployment
metadata:
  name: degoog-valkey
  namespace: apps
  labels:
    app: degoog-valkey

spec:
  replicas: 1

  selector:
    matchLabels:
      app: degoog-valkey

  template:
    metadata:
      labels:
        app: degoog-valkey

    spec:
      containers:
        - name: valkey

          image: valkey/valkey:9-alpine

          command:
            - valkey-server
            - "--save"
            - ""
            - "--appendonly"
            - "no"

          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 256Mi

          volumeMounts:
            - name: valkey-data
              mountPath: /data

      volumes:
        - name: valkey-data
          persistentVolumeClaim:
            claimName: degoog-valkey-data