apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: apps
  labels:
    app: homepage

spec:
  replicas: 1

  selector:
    matchLabels:
      app: homepage

  template:
    metadata:
      labels:
        app: homepage

    spec:
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest

          ports:
            - containerPort: 3000

          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "home.williampring.ca"

          volumeMounts:
            # Keep these as individual subPath mounts.
            # This allows Homepage to create /app/config/logs.
            - name: config
              mountPath: /app/config/settings.yaml
              subPath: settings.yaml

            - name: config
              mountPath: /app/config/services.yaml
              subPath: services.yaml

            - name: config
              mountPath: /app/config/widgets.yaml
              subPath: widgets.yaml

            - name: config
              mountPath: /app/config/bookmarks.yaml
              subPath: bookmarks.yaml

          resources:
            requests:
              cpu: 25m
              memory: 64Mi

            limits:
              memory: 256Mi

      volumes:
        - name: config
          configMap:
            name: homepage-config