---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-wildcard
  namespace: kube-system
spec:
  secretName: media-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.media.williampring.ca"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-wildcard
  namespace: kube-system
spec:
  secretName: monitoring-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.monitoring.williampring.ca"
