---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-wildcard
  namespace: vpn
spec:
  secretName: media-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.media.williampring.ca"
