apiVersion: v1
kind: Service
metadata:
  name: komga
  namespace: media
  labels:
    app: komga
spec:
  type: NodePort           # keeps a ClusterIP too → Ingress/domain still works
  selector:
    app: komga
  ports:
    - port: 25600
      targetPort: 25600
      nodePort: 30600      # LAN access: http://<node-LAN-IP>:30600
